/**
 * Cloudflare Workers entry point.
 *
 * The .open-next/worker.js generated by @opennextjs/cloudflare only has a fetch
 * handler, so the scheduled handler called by Cron Triggers is added here.
 * It replaces Vercel Cron (the crons in vercel.json).
 *
 * The cron routes are GETs protected by Bearer CRON_SECRET, so the Worker builds
 * the same request internally and passes it to the fetch handler. Set CRON_SECRET
 * with `wrangler secret put CRON_SECRET`.
 *
 * .open-next/ is build output and is in .gitignore. This file is kept outside
 * tsconfig (plain JS) so that the pre-build type check does not try to resolve
 * imports that have not been generated yet.
 */
import openNextHandler from "./.open-next/worker.js";

export { DOQueueHandler } from "./.open-next/worker.js";
export { DOShardedTagCache } from "./.open-next/worker.js";
export { BucketCachePurge } from "./.open-next/worker.js";

// Keep this in sync with triggers.crons in wrangler.jsonc.
const CRON_PATHS = {
  "0 21 * * *": "/api/cron/daily-digest", // JST 06:00
  "0 4 * * *": "/api/cron/cleanup",
};

const worker = {
  fetch: openNextHandler.fetch,

  async scheduled(controller, env, ctx) {
    const path = CRON_PATHS[controller.cron];
    if (!path) {
      console.error(`[cron] 未知のスケジュール: ${controller.cron}`);
      return;
    }
    const request = new Request(`https://ai-news-feed-app.saitotakuya0719.workers.dev${path}`, {
      headers: { authorization: `Bearer ${env.CRON_SECRET}` },
    });
    ctx.waitUntil(
      openNextHandler.fetch(request, env, ctx).then(
        (res) => console.log(`[cron] ${path} -> ${res.status}`),
        (err) => console.error(`[cron] ${path} 失敗`, err),
      ),
    );
  },
};

export default worker;
